### ISSUE TITLE
Cant build for BBC Micro:bit v2

### ISSUE THREAD

**Issue by BrellyDev** [koenvervloesem/openhaystack-zephyr#2]
Hi, Im trying to build the firmware for a BBC Micro:Bit V2 when I run this command:

west build -p auto -b bbc_microbit_v2 -s app

I get the following error

usage: west [-h] [-z ZEPHYR_BASE] [-v] [-V] <command> ...
west: error: argument <command>: invalid choice: 'build' (choose from 'init', 'update', 'list', 'manifest', 'diff', 'status', 'forall', 'help', 'config', 'topdir', 'selfupdate')

**Comment by koenvervloesem** [comment]
Hi, I'm seeing this just now. What was the reason for the error? Incorrect directory where you ran west, right?
