### ISSUE TITLE
is this able to run on the nrf51822?

### ISSUE THREAD

**Issue by beckmx** [koenvervloesem/openhaystack-zephyr#3]
Hello there, I was checking your repo and noticed that you focused more on the nrf52? I was wondering if this can be targetted to the nrf51 as well

**Comment by koenvervloesem** [comment]
As far as I know, I've used nothing specific to the nRF52 SoC in the code, it's just that these are the only ones I had available for testing. Have a look at Zephyr's [supported boards](https://docs.zephyrproject.org/latest/boards/index.html), there are a couple of nRF51 devices there (for instance the [nRF51 Dongle](https://docs.zephyrproject.org/latest/boards/arm/nrf51dongle_nrf51422/doc/index.html) is using an nRF51822). With a supported board, it should just be a case of using the right `$BOARD` in the build command `west build -p auto -b $BOARD -s app`.

**Comment by beckmx** [comment]
I added this board:

```
[env:nrf51822]
platform = nordicnrf51
board = nrf51_dk
framework = zephyr
upload_protocol = stlink
debug_tool = stlink
```

I am not an advanced user for nordic devices but after flashing the device I am not seeing it sends data, at least not in the openhaystack mac app, could it be the softdevice?

**Comment by koenvervloesem** [comment]
Can you check with a Bluetooth scanner what the device is sending? For example with [HumBLE Explorer](https://humble-explorer.readthedocs.io) or with [nRF Connect for Mobile](https://www.nordicsemi.com/Products/Development-tools/nrf-connect-for-mobile).

**Comment by beckmx** [comment]
I checked on humble, very nice interface, I think the bt address should be a good add-on, there are tons of devices around me, let me go to a less noisy place

**Comment by koenvervloesem** [comment]
If you're using HumBLE Explorer on macOS, you can get the actual Bluetooth addresses of scanned devices with the `-m` option. However, this is relying on an unsupported internal API and doesn't work on all macOS versions (that's why it isn't enabled by default).

With the default public key "OFFLINEFINDINGPUBLICKEYHERE!" in the firmware you flashed, you should clearly see part of this string in the advertising data in the Bluetooth scanner.

**Comment by beckmx** [comment]
I managed to understand more of humble, so basically the advertising key is what I look for, right? I changed the code like this:

`static char public_key[28] = {0xb9, 0xa5, 0x97, 0x50, 0x6, xyz.... };`

according to the code my address should start with 0xF9... but it doesnt show up, one important thing is I am manually uploading the file called zephyr to the nrf51822, i tried with both zephyr.bin and zephyr.hex but no luck yet :(

**Comment by koenvervloesem** [comment]
Maybe try to flash the [Blinky](https://docs.zephyrproject.org/latest/samples/basic/blinky/README.html) example from Zephyr first to verify whether the firmware is really running on the device. This should blink the default user LED.
