### ISSUE TITLE
AttributeError in openhaystack-zephyr when using nrfutil for package generation

### ISSUE THREAD

**Issue by marcolucc** [koenvervloesem/openhaystack-zephyr#5]
When attempting to generate a package using the nrfutil tool with the command nrfutil pkg generate, an AttributeError is raised within the openhaystack-zephyr project. This error occurs specifically when the tool attempts to iterate through the firmwares_data dictionary, leading to the error message "AttributeError: 'dict' object has no attribute 'iteritems'".

`openhaystack-zephyr % nrfutil pkg generate --hw-version 52 --sd-req=0x00 \
        --application build/zephyr/zephyr.hex \
        --application-version 1 openhaystack.zip
 
|===============================================================|
|##      ##    ###    ########  ##    ## #### ##    ##  ######  |
|##  ##  ##   ## ##   ##     ## ###   ##  ##  ###   ## ##    ## |
|##  ##  ##  ##   ##  ##     ## ####  ##  ##  ####  ## ##       |
|##  ##  ## ##     ## ########  ## ## ##  ##  ## ## ## ##   ####|
|##  ##  ## ######### ##   ##   ##  ####  ##  ##  #### ##    ## |
|##  ##  ## ##     ## ##    ##  ##   ###  ##  ##   ### ##    ## |
| ###  ###  ##     ## ##     ## ##    ## #### ##    ##  ######  |
|===============================================================|
|You are not providing a signature key, which means the DFU     |
|files will not be signed, and are vulnerable to tampering.     |
|This is only compatible with a signature-less bootloader and is|
|not suitable for production environments.                      |
|===============================================================|
 
Traceback (most recent call last):
  File "/usr/local/bin/nrfutil", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nordicsemi/__main__.py", line 867, in generate
    package.generate_package(zipfile_path)
  File "/usr/local/lib/python3.11/site-packages/nordicsemi/dfu/package.py", line 403, in generate_package
    for key, firmware_data in self.firmwares_data.iteritems():
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'iteritems'`

**Comment by koenvervloesem** [comment]
What version of nrfutil is this? I'm using nrfutil daily with Python 3.10 and I've never seen this error. The only similarly looking issue I have found is https://github.com/makerdiary/nrf52840-mdk-usb-dongle/issues/56.

**Comment by marcolucc** [comment]
I'm using version 5.2.0 of nrfutil and python 3.11

**Comment by koenvervloesem** [comment]
Can you try the latest nrfutil, 6.1.7?

**Comment by marcolucc** [comment]
Downgrading to python3.10 and nrfutil 6.1.7 solved the issue
